### PR TITLE
Create archway-passage.json, added Validatrium relay

### PR DESCRIPTION
**Pull request by Validatrium**

### CODE REVIEW

**Comment by emperorjm** [comment]
HI @Validatrium. There is an issue with the trusting period being used:

```
Checking client 07-tendermint-84 on chain archway
trusting_period: 864000s, required_trusting_period: 1209600s, unbonding_period: 1814400s
Checking client 07-tendermint-3 on chain passage
trusting_period: 1209600s, required_trusting_period: 1209600s, unbonding_period: 1814400s
Error: Incorrect trusting period for all or some clients 
```

See the following for the correct values to be used: https://github.com/archway-network/networks#requirements-for-the-ibc-channel

**Comment by Validatrium** [comment]
@emperorjm need your advice, do we need to full recreate relay, or may update client configuration?

**Comment by emperorjm** [comment]
> @emperorjm need your advice, do we need to full recreate relay, or may update client configuration?

I believe the only way to update those params is via a governance proposal so the easiest way would be to set up a new one once no funds are stuck in the current channel.

**Comment by Validatrium** [comment]
@emperorjm the issue resolved

**Review by emperorjm — APPROVED** [review]
LGTM

**Pull request merged**
