### PR TITLE
Update chain.json

### PR DESCRIPTION
**Pull request by svv28**
Added seed-node, hosted by Pro-Nodes75 validator

### CODE REVIEW

**Review by jlehtimaki — CHANGES_REQUESTED** [review]
The node does not respond and resolve the  conflicts

**Comment by svv28** [comment]
this is a seed node, which is providing addrbook.json only.

i've just checked it: pinged my domain `archway.seed.node75.org` and it is pinging;
restarted mine mainnet node with clear addrbook and with only our seed node in config.toml :
`86bd5cb6e762f673f1706e5889e039d5406b4b90@archway.seed.node75.org:10256`

everything is working fine. please, check one more time

**Comment by shahbazn** [comment]
closing stale PR

**Comment by svv28** [comment]
my seed node is working, and domain is pinging. did anyone checked it one more time?

please, check it, and add my endpoint to docks.

**Pull request closed without merging**
