### PR TITLE
add vidulum relayer ops

### PR DESCRIPTION
**Pull request by Corey-Code**

### CODE REVIEW

**Comment by emperorjm** [comment]
Hi @Corey-Code. The trusting period seems to be invalid:

```
Checking client 07-tendermint-80 on chain archway
trusting_period: 1540800s, required_trusting_period: 1209600s, unbonding_period: 1814400s
Checking client 07-tendermint-49 on chain vidulum
trusting_period: 1540800s, required_trusting_period: 1209600s, unbonding_period: 1814400s
```

**Comment by Corey-Code** [comment]
> Hi @Corey-Code. The trusting period seems to be invalid (https://github.com/archway-network/networks/actions/runs/7997039892/job/21873858436?pr=320):
> 
> ```
> Checking client 07-tendermint-80 on chain archway
> trusting_period: 1540800s, required_trusting_period: 1209600s, unbonding_period: 1814400s
> Checking client 07-tendermint-49 on chain vidulum
> trusting_period: 1540800s, required_trusting_period: 1209600s, unbonding_period: 1814400s
> ```

I'll take a look thanks

**Comment by Corey-Code** [comment]
Apologies, did not mean to close this.

**Comment by Corey-Code** [comment]
Once the clients/channels etc have been created, is there a way to update the trusting period? I am currently using rly and it seems that can only be set at the time of creation.

**Comment by emperorjm** [comment]
> Once the clients/channels etc have been created, is there a way to update the trusting period? I am currently using rly and it seems that can only be set at the time of creation.

The only way to update those params is via a governance proposal so the easiest way would be to set up a new one once no funds are stuck in the current channel and the channel is not being utilized.

**Pull request merged**
