### PR TITLE
Create archway-terra2.json

### PR DESCRIPTION
**Pull request by dylanschultzie**

### CODE REVIEW

**Comment by dylanschultzie** [comment]
https://github.com/cosmos/chain-registry/blob/master/_IBC/archway-terra2.json

**Review by jlehtimaki — CHANGES_REQUESTED** [review]
@dylanschultzie can you please create the channel with proper trusting periods?
Seems like there's no funds been transferred yet.

https://www.mintscan.io/archway/relayers/channel-48/terra/channel-263

**Comment by dylanschultzie** [comment]
@jlehtimaki this needs reran manually it looks like, as I recreated the channels with the appropriate trust periods

**Comment by jlehtimaki** [comment]
> @jlehtimaki this needs reran manually it looks like, as I recreated the channels with the appropriate trust periods

I ran it and still getting the same result.

**Comment by dylanschultzie** [comment]
@jlehtimaki

**Review by jlehtimaki — APPROVED** [review]

**Pull request merged**
